export const stageNames = [
    "Clocaenog Mid",
    "Penmachno South",
    "Myherin",
    "Hafren",
    "Dyfi",
    "Gartheiniog",
    "Chirdonhead",
    "Falstone",
    "Kershope",
    "Pundershaw",
    "Riccarton",
    "Newcastleton",
    "Twiglees",
    "Yair",
    "Cardrona",
    "Black Lock",
    "Glentrool",
    "Ae",
    "Moon and Star",
    "Bothwell",
    "Whitchester",
    "Eccles",
    "Langton",
    "Fogo",
    "Hamilton's Folly",
    "Tyrones Ditches",
    "Feeney",
    "Parkanaur",
    "Lisnamuck",
    "Tardree",
    "Port Soderick",
    "Ballagyr",
    "Curraghs",
    "Tholt-y-Will",
    "Injerbreck",
    "Cringle"
];